app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    // return view('welcome');
    return view('public.index');
});


/**
 * Admin Controller
 * Handles requests from site administrators
 */
Route::resource('admin/billing', 'AdminInvoiceController');

Route::get('admin/places', [
    'as' => 'admin.places', 'uses' => 'AdminController@places'
]);
Route::get('admin/pricing', [
    'as' => 'admin.pricing', 'uses' => 'AdminController@pricing'
]);
Route::put('admin/pricing', [
    'as' => 'admin.pricing', 'uses' => 'AdminController@pricingUpdate'
]);
Route::resource('admin', 'AdminController');
Route::resource('admin/billing', 'AdminInvoiceController');

/**
 * User Controller
 * Handles requests to interact with a user's account.
 */
Route::resource('user', 'UserController');

/**
 * User Places Controller
 * Handles requests to interact with a user's places.
 */
Route::resource('user.places', 'UserPlaceController');


/**
 * User Places Controller
 * Handles requests to interact with a user's places.
 */
Route::resource('user.invoices', 'UserInvoiceController');

/**
 * User Images Controller
 * Handles requests to interact with a user's images.
 */
Route::resource('user.images', 'UserImageController');

/**
 * Api Controllers
 * Handles api requests for front end application.
 */
Route::resource('api/tags', 'ApiTagsController');
Route::resource('api/user', 'ApiUsersController');

/**
 * User Registration and Login
 * Handles new user creation and user login.
 */
Route::get(	'auth/register',
			'Auth\AuthController@getRegister');
Route::post('auth/register',
 			'Auth\AuthController@postRegister');
Route::get(	'auth/login',
			'Auth\AuthController@getLogin');
Route::post('auth/login',
 			'Auth\AuthController@postLogin');
Route::get('auth/logout',
		   'Auth\AuthController@logout');
/**
 * Logs a user out.
 */
Route::get('logout',
		   'Auth\AuthController@logout');
/**
 * Registration and Login Aliases
 */
Route::get('register', [
	'as' => 'register',
	'uses' => 'Auth\AuthController@getRegister'
]);
Route::post('register', [
	'as' => 'register',
	'uses' => 'Auth\AuthController@postRegister'
]);
Route::get('login', [
	'as' => 'login',
	'uses' => 'Auth\AuthController@getLogin'
]);
Route::post('login', [
	'as' => 'login',
	'uses' => 'Auth\AuthController@postLogin'
]);

resources/views/admin/invoices/create.blade.php
@extends('templates.main')

@section('pageTitle', "Billing Run - Top 5 Admin")
@section('title', "Billing Run <small>Top 5 Admin</small>")

@section('content')


<section class="container">
@if( ! $users->sum('BillingDisplays'))
	<h4>Not Enough Billable Displays</h4>
	<p class="lead">Currently, there are no users who have reached the minimum threshold for billing.</p>
@else
<h4>Forecast</h4>
<p>This is an estimate of the current billing period if you were to run billing now. Only users who have reach them minimum threshold of {{$pricing->min('minimum_displays')}} displays will be billed in this statement run. </p>

<table class="table table-responsive table-striped">
	<thead>
		<tr>
			<th>User</th>
			<th class="text-center">Clicks</th>
			<th class="text-center">Displays</th>
			<th class="text-right">Per Unit</th>
			<th class="text-right">Total</th>
		</tr>
	</thead>
	<tbody>
	@foreach($users as $user) 
		@if($user->lastDisplays > $pricing->min('minimum_displays'))
		<tr>
			<th> <strong>{!!$user->name!!}</strong></th>
			<td class="text-center"> {!! $user->lastClicks !!} </td>
			<td class="text-center"> {!! $user->lastDisplays !!} </td>
			@foreach($pricing as $price)
				@if($user->lastDisplays > $price->minimum)
					<td class="text-right">${{$price->price}}</td>
					<td class="text-right">${!! number_format($price->price * $user->lastDisplays,2) !!}</td>
					@break
				@endif
			@endforeach
		</tr>
		@endif
	@endforeach
	</tbody>
</table>

{!! Form::open(['method' => 'POST', 'url' => route('admin.billing.store')]) !!}
	{!!Form::hidden('run_billing', true)!!}
	<button type="submit" class="btn btn-block btn-success"> Run Billing Now </a>
{!! Form::close() !!}
@endif 

<p class="lead"><a href="{{route('admin.billing.index')}}" title="Return to Billing">Return to Billing</a>

</section>
<section>
<h4>Pricing Table</h4>
<ul>
	@foreach($pricing as $price)
		<li>
			Min Clicks: {{$price->minimum}} <br>
			Price: ${{$price->price}}
	@endforeach
</ul>
</section>

@endsection

resources/views/admin/invoices/index.blade.php
@extends('templates.main')

@section('pageTitle', "Invoices - Top 5 Admin")
@section('title', "Invoices <small>Top 5 Admin</small>")

@section('content')
<article>
<section class="container">

<a href="{!! route('admin.billing.create') !!}" class="btn btn-default col-sm-4">
	<span class="glyphicon glyphicon-usd"></span>
	Do Billing Run
</a>
</section>
<section class="container row">
	<h3>Past Statements</h3>
	<table class="table table-responsive table-striped">
		<thead>
			<th> Run Number </th>
			<th> Date Run </th>
			<th> Invoices </th>
			<th> Total </th>
		</thead>
		<tbody>
		@foreach($statements as $statement) 
		<tr>
			<td>
				{{$statement->id}}
			</td>
			<td>
				{{$statement->run_at->format('d-M-Y')}}
			</td>
			<td>
				{{$statement->invoiceCount}}
			</td>
			<td>
				{{$statement->runTotal}}
			</td>
			<td>
				@include('templates.partials.button', array(
					'link'  => route('admin.billing.show', $statement->slug),
					'class' => 'btn btn-block btn-default',
					'icon'  => 'search',
					'title' => "View Statement #{$statement->id}",
					'text'  => "View"
				))
			</td>
		</tr>
		@endforeach
		</tbody>
	</table>
	</section>

	<hr> 
</article>
@endsection

resources/views/admin/invoices/show.blade.php
@extends('templates.main')

@section('pageTitle', "$statement->statementNumber - Top 5 Admin")
@section('title', "$statement->statementNumber <small>Top 5 Admin</small>")

@section('content')
<article>
<section class="container row">

	<p class="lead text-left col-xs-4"> 
		<strong class="">Date Run:</strong>
		<span class="">{{$statement->run_at->format('d-M-Y')}}</span>
	</p>
	<p class="lead text-center col-xs-4"> 
		<strong class="">Invoices:</strong>
		<span class="">{{$statement->invoiceCount}}</span>
	</p>
	<p class="lead text-right col-xs-4"> 
		<strong class="">Total:</strong>
		<span class="">{{$statement->runTotal}}</span>
	</p>
				
</section>
	@include('partials.table-user-invoices', ['invoices' => $statement->invoices])
<footer>
	<a class="btn btn-lg btn-block btn-primary" href="{{route('admin.billing.index')}}" title="Back to Billing">Back to Billing</a>
</footer>	
</article>
@endsection