app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    // return view('welcome');
    return view('public.index');
});


/**
 * Admin Controller
 * Handles requests from site administrators
 */
Route::resource('admin/billing', 'AdminInvoiceController');

Route::get('admin/places', [
    'as' => 'admin.places', 'uses' => 'AdminController@places'
]);
Route::get('admin/pricing', [
    'as' => 'admin.pricing', 'uses' => 'AdminController@pricing'
]);
Route::put('admin/pricing', [
    'as' => 'admin.pricing', 'uses' => 'AdminController@pricingUpdate'
]);
Route::resource('admin', 'AdminController');
Route::resource('admin/billing', 'AdminInvoiceController');

/**
 * User Controller
 * Handles requests to interact with a user's account.
 */
Route::resource('user', 'UserController');

/**
 * User Places Controller
 * Handles requests to interact with a user's places.
 */
Route::resource('user.places', 'UserPlaceController');


/**
 * User Places Controller
 * Handles requests to interact with a user's places.
 */
Route::resource('user.invoices', 'UserInvoiceController');

/**
 * User Images Controller
 * Handles requests to interact with a user's images.
 */
Route::resource('user.images', 'UserImageController');

/**
 * Api Controllers
 * Handles api requests for front end application.
 */
Route::resource('api/tags', 'ApiTagsController');
Route::resource('api/user', 'ApiUsersController');

/**
 * User Registration and Login
 * Handles new user creation and user login.
 */
Route::get(	'auth/register',
			'Auth\AuthController@getRegister');
Route::post('auth/register',
 			'Auth\AuthController@postRegister');
Route::get(	'auth/login',
			'Auth\AuthController@getLogin');
Route::post('auth/login',
 			'Auth\AuthController@postLogin');
Route::get('auth/logout',
		   'Auth\AuthController@logout');
/**
 * Logs a user out.
 */
Route::get('logout',
		   'Auth\AuthController@logout');
/**
 * Registration and Login Aliases
 */
Route::get('register', [
	'as' => 'register',
	'uses' => 'Auth\AuthController@getRegister'
]);
Route::post('register', [
	'as' => 'register',
	'uses' => 'Auth\AuthController@postRegister'
]);
Route::get('login', [
	'as' => 'login',
	'uses' => 'Auth\AuthController@getLogin'
]);
Route::post('login', [
	'as' => 'login',
	'uses' => 'Auth\AuthController@postLogin'
]);

app/User.php
<?php

namespace top5;

use Illuminate\Foundation\Auth\User as Authenticatable;

// Sluggable Methods
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use top5\Model\UserTraits;
use top5\Model\Price;

class User extends Authenticatable
{
    use SluggableTrait;
    use UserTraits;

    public $apiPlaceFields = array(
        'id',
        'user_id',
        'name',
        'slug',
        'description',
        'ratings',
        'address',
        'suburb',
        'postcode',
        'state',
        'lat',
        'lng',
    );

    /**
     * Defines a one to many relationship with Places
     * @return top5\Place
     */
    public function places() {
        return $this->hasMany('top5\Model\Place');
    }
    /**
     * Returns a user's places for a user list api request.
     * @return top5\Place
     */
    public function apiUserListPlaces() {
        return $this->hasMany('top5\Model\Place', 'user_id', 'id')
                    ->select($this->apiPlaceFields)
                    ->orderBy('ratings','desc');
    }
    /**
     * Returns a user's places for a single user api request.
     * @return top5\Place
     */
    public function apiUserSinglePlaces() {
        return $this->hasMany('top5\Model\Place', 'user_id', 'id')
                    ->select($this->apiPlaceFields)
                    ->orderBy('ratings','desc');
    }


    /**
     * Returns one to many places with public attributes.
     * @return top5\Place
     */


    /**
     * Defines a one to many relationship with images.
     * @return top5\Image
     */
    public function images() {
        return $this->hasMany('top5\Model\Image');
    }

    /**
     * Defines a one to many relationship with images.
     * @return top5\Image
     */
    public function invoices() {
        return $this->hasMany('top5\Model\Invoice\Invoice');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'username',
        'firstname',
        'lastname',
        'description',
        'slug',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_admin' => 'boolean',
    ];

    /**
     * Makes user sluggable.
     * @var array
     */
    protected $sluggable = array(
        'build_from' => 'username',
        'save_to' => 'slug',
        'on_update' => true,
    );

    /**
     * Concatenates and returns the user's full name.
     * @return string
     */
    public function getFullNameAttribute() {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * Returns the user's full name with a link to their page.
     * @return string
     */
    public function getNameLinkAttribute() {
        return  $this->userLink( $this->getFullNameAttribute() );
    }

    /**
     * Returns the user name with a link to their page.
     * @return string
     */
    public function getUsernameLinkAttribute() {
        return $this->userLink( '&#64;' . $this->username );
    }
    /**
     * Calculates and returns the clicks since last bill.
     * @return  integer
     */
    public function getLastClicksAttribute() {
        return $this->places->sum('clicks_after_last_bill');
    }

    /**
     * Calculates and returns the total displays since last bill.
     * @return  integer
     */
    public function getLastDisplaysAttribute() {
        return $this->places->sum('displays_after_last_bill');
    }

    /**
     * Checks to see if the total displays for a user's places reaches
     * the minimum threshold for billing and returns total or 0.
     * @return integer
     */
    public function getBillingDisplaysAttribute() {
        $min_displays = Price::min('minimum_displays');
        if ($this->places->sum('displays_after_last_bill') >= $min_displays) {
            return $this->places->sum('displays_after_last_bill');
        } else {
            return 0;
        }
    }

    /**
     * Returns a link to this user's page.
     * @param  string $str Text to display for the link.
     * @return string
     */
    protected function userLink($str) {
        return '<a href="'.route('user.show', $this->slug).'">' . $str . "</a>";
    }

}

app/Http/Controllers/UserController.php
<?php

namespace top5\Http\Controllers;

use Auth;
use DB;
use Illuminate\Pagination\Paginator as Paginator;

use Illuminate\Http\Request;

use top5\Http\Requests;
use top5\Http\Requests\UserRequest;

use top5\User;
use top5\Model\Place;
use top5\Model\Invoice\Invoice;

use top5\Http\Controllers\SortableTraits;
use top5\Model\UserTraits;


class UserController extends Controller
{
    use SortableTraits;
    use UserTraits;
    /**
     * Restricts access to authenticated users only.
     */
    public function __construct()
    {
        $this->middleware(['auth', 'user']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ( Auth::user()->is_admin !== true ) {
            return redirect()->route('user.show', ['slug' => $user->slug]);
        } else {
            $this->setOptions($request);
            $session = $request->session()->all();
            
            /**
             * Determine the appropriate query for sorting places.
             */
            if ($this->sortUserField() != 'placeCount') {
                $users = User::orderBy($this->sortUserField(), $this->sortUserValue())
                             ->paginate($this->results_per_page());
            } else {
                $users = User::leftJoin('places', 'users.id', '=', 'places.user_id')
                             ->selectRaw('users.*, count(places.id) as placeCount')
                             ->groupBy('users.id')
                             ->orderBy('placeCount', $this->sortUserValue())
                             ->paginate($session["results_per_page"]);
            }
            return view('user.admin')->with('users', $users);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        return redirect()->route('user.show', ['slug' => Auth::user()->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug, UserRequest $request)
    {
        $user = User::findBySlug($slug);

        // Set request options and get session data
        $this->setOptions($request);
        $session = $request->session()->all();

        $user->places = Place::where('user_id', '=', $user->id)
                             ->paginate($session["results_per_page"],['*'],'places_page');

        $user->invoices = Invoice::where('user_id', '=', $user->id)
                                 ->orderBy('id', 'DESC')
                                 ->paginate($session["results_per_page"],['*'],'invoice_page');;

        return view('user.index')->with('user', $user);
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $user = $this->userAdminSlug($slug);
        return view('user.edit')->with('user', $user);
    }

    /**
     * Update the specified user in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $slug)
    {
        $user = User::findBySlug($slug);
        $user->fill($request->all());
        $user->save();
        
        return redirect()->route('user.show', $user->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $message = null;
        if( Auth::user()->is_admin) {
            $user = User::findBySlug($slug);
            $user->delete();
            $message = "<strong>$user->name</strong> has been deleted.";
        }
        return redirect()->route('user.index')
                ->with('flash_message', $message);
    }
}

resources/views/user/admin.blade.php
@extends('templates.main')

@section('pageTitle', "Manage Users - Top 5")
@section('title', "Manage Users	 <small>Top 5</small>")

@section('content')


<section class="container">

<article class="panel panel-primary">
	<header class="panel-heading container-fluid">
		<h4 class="col-xs-6">Title</h4>
		<p class="col-xs-6 text-right">
			@include('partials.input-results_per_page')
		</p>
	</header>

	<table class="table table-striped table-hover container">
	<thead>
		<tr>
			<th class="col-sm-3">
				@include('partials.link-sorting', array(
					'modelName' => 'user',
					'label' => 'User',
					'field' => 'username',
					'title' => 'Sort by User Name',
					'route' => Request::route()->getName(),
				))
			</th>
			<th class="col-sm-3 hidden-xs hidden-sm">
				@include('partials.link-sorting', array(
					'modelName' => 'user',
					'label' => 'Join Date',
					'field' => 'created_at',
					'title' => 'Sort by Join Date',
					'route' => Request::route()->getName(),
				))

			</th>
			<th class="hidden-xs text-center">
				@include('partials.link-sorting', array(
					'modelName' => 'user',
					'label' => 'Places',
					'field' => 'placeCount',
					'title' => 'Sort by Place Count',
					'route' => Request::route()->getName(),
				))
			</th>
			<th class="col-md-3 col-sm-4 col-xs-5 text-center">
				Actions
			</th>
		</tr>
	</thead>
	<tbody>
@foreach($users as $user) 
		<tr>
			<th> 
				{!!$user->usernameLink!!}
				<br class="visible-xs">
				<span class="hidden-xs">/</span>
				{!!$user->nameLink!!} 
		 	</th>
			<td class="hidden-xs hidden-sm"> 
				{!! $user->created_at->format('d M Y') !!}
			</td>
			<td class="hidden-xs text-center"> 
				{{$user->places->count()}}
			</td>
			<td class="text-left">
				@include('templates.partials.button', array(
					'link'  => route('user.show', ['slug' => $user->slug]),
					'icon'  => 'search',
					'title' => "View $user->name",
					'text'  => 'View'
				))
				@include('templates.partials.button', array(
					'link'  => route('user.edit', ['slug' => $user->slug]),
					'icon'  => 'pencil',
					'title' => "Edit $user->name",
					'text'  => 'Edit'
				))

				@if(! $user->is_admin)
				@include('templates.partials.button-delete', [
					'warning' => "This will permanently delete all of $user->name's profile and billing data, and {$user->places->count()} places.",
					'model' => $user,
					'route' => route('user.destroy', ['user' => $user->slug]),

				])
				@endif
			</td>
		</tr>
@endforeach
	</tbody>
	<tfoot>
		<td colspan="4" class="text-center">{{ $users->links() }}</td>
	</tfoot>
	{{-- @endforeach --}}
</table>
</article>

</section>


@endsection

resources/views/user/edit.blade.php
@extends('templates.partials.form')

@section('formPageTitle', "Update Account")

@section('formTitle', "$user->nameLink <small>Update Your Account</small>")

@section('form')

	{!! Form::model($user, array(
		'method' => 'PUT',
		'url' => route('user.update', $user->slug),
		'class' => 'form container'
	)) !!}

	@include('user.form-user', ["model" => $user])

	<p class="form-group col-xs-12">
		{!! Form::submit(
			'Update Your Account', [
			'class' => 'btn btn-block btn-primary'
		])!!}
	</p>

	{!! Form::close() !!}

@endsection

resources/views/user/form-user.blade.php
	<fieldset>
		<legend>User Account</legend>
		@include('partials.input-email', ['model' => $model])
		@include('partials.input-username', ['model' => $model])
	</fieldset>
	<fieldset>
		<legend>Profile</legend>
		@include('partials.input-name', ['model' => $model])
		@include('partials.input-description', [
			'model' => $model, 
			'helpText' => 'Add a brief description about the products and services your businesses offer. <br> <small>(255 characters max)</small>'
		])
	</fieldset>

resources/views/user/index.blade.php
@extends('templates.main')

@section('pageTitle', "Your Account")
@section('title', "$user->fullName <small>Account</small>")

@section('content')


<section class="row container">
	<p class="col-sm-6">
		<a href="{{ route('user.edit', $user->slug) }}" class="btn btn-default btn-block">
			<span class="glyphicon glyphicon-pencil"></span>
			Edit Profile
		</a>
	</p>
	<p class="col-sm-6">
		<a href="#" class="btn btn-default btn-block">
			<span class="glyphicon glyphicon-lock"></span>
			Change Password
		</a>
	</p>
</section>

<section class="row places">
	@include('partials.table-user-places', ['places' => $user->places])
	<p> <a class="btn btn-block btn-primary btn-lg" href="{{route('user.places.index', $user->slug)}}">View All Places</a> </p>
</section>

@if( ! $user->is_admin)
<section class="row invoices">
	@include('partials.table-user-invoices', ['invoices' => $user->invoices])
	<a class="btn btn-block btn-primary btn-lg" href="{{route('user.invoices.index', $user->slug)}}">View All Invoices</a>
</section>
@endif

@endsection

resources/views/user/password.blade.php
@extends('templates.main')

@section('pageTitle', "Update Password")
@section('title', "$user->name <small>Update Your Password</small>")

@section('content')

@if (count($errors) > 0) 
<ul>
	@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
	@endforeach
</ul>
@endif

{!! Form::model($user, array(
	'method' => 'POST',
	'url' => route('user.password', $user->slug),
	'class' => 'form container'
)) !!}
<p class="form-group col-xs-12">
	{!! Form::label('password', 'Current Password') !!}
	{!! Form::password('old', [
		"class" => "form-control",
		"placeholder" => "Enter your current password"
	]) !!}
</p>
<p class="form-group col-xs-12">
	{!! Form::label('new_password', 'New Password') !!}
	{!! Form::password('new', [
		"class" => "form-control",
		"placeholder" => "Enter your new password"
	]) !!}
</p>
<p class="form-group col-xs-12">
	{!! Form::password('new_confirmation', [
		"class" => "form-control",
		"placeholder" => "Confirm your new password"
	]) !!}
</p>
<p class="form-group col-xs-12">
	{!! Form::submit('Update Your Password', ['class' => 'btn btn-block btn-primary'])!!}
</p>

{!! Form::close() !!}

@endsection